name:
kind: secret
get:
pipeline:
  ssh-commands:
    image: appleboy/drone-ssh
    settings:
    secrets: [ ssh_key,host,username]
    port: 22
    script:
      - docker exec -i php74 php ./${DRONE_REPO_NAME}/artisan down
      - docker exec -i php74 bash -c "git -C ${DRONE_REPO_NAME} checkout . && git -C ${DRONE_REPO_NAME} reset --hard"
      - docker exec -i php74 bash -c "git -C ${DRONE_REPO_NAME} pull"
      - docker exec -i php74 bash -c "cd ${DRONE_REPO_NAME} && composer update && npm install -y && npm run dev"
      - docker exec -i php74 php ./${DRONE_REPO_NAME}/artisan up
    when:
      status: [ success ]
  notification:
    image: appleboy/drone-discord
    secrets: [ discord_webhook_id,discord_webhook_token ]
    when:
      status: [ success,failure ]
