name:
kind: secret
get:
pipeline:
  ssh-commands:
    image: appleboy/drone-ssh
    settings:
    secrets: [ ssh_key,host,username]
    port: 22
    script:
      - sh project-update.sh
    when:
      status: [ success ]
  notification:
    image: appleboy/drone-discord
    secrets: [ discord_webhook_id,discord_webhook_token ]
    when:
      status: [ success,failure ]
