// Actions
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
/*chart*/
export const CHANGE_MONEY_STATUS = 'chart/CHANGE_MONEY_STATUS';
export const CHANGE_MONTH_BALANCE = 'chart/CHANGE_MONTH_BALANCE';
export const SET_CHART_DATA = 'chart/SET_CHART_DATA';
/*dataTable*/
export const SET_TABLE_SELECT = 'dataTable/SET_TABLE_SELECT';
export const PUSH_TABLE_SELECT = 'dataTable/PUSH_TABLE_SELECT';
export const SPLICE_TABLE_SELECT = 'dataTable/SPLICE_TABLE_SELECT';
/*datePick*/
export const CHANGE_DATE = 'datePick/CHANGE_DATE';
/*dateRange*/
export const CHANGE_DATE_RANGE = 'dateRange/CHANGE_DATE_RANGE';
/*exchangeRate*/
export const CHANGE_CHART_EXCHANGE_LINE = 'exchangeRate/CHANGE_CHART_EXCHANGE_LINE';
export const CHANGE_EXCHANGE_RATES_LIST = 'exchangeRate/CHANGE_EXCHANGE_RATES_LIST';
export const CHANGE_CURRENCY = 'exchangeRate/CHANGE_CURRENCY';
/*financial*/
export const SET_PROVIDE_AJAX_DATA = 'financial/SET_PROVIDE_AJAX_DATA';
export const SET_STATISTICS = 'financial/SET_STATISTICS';
export const SELECT_DATA = 'financial/SELECT_DATA';
export const SORT_PROVIDE_STATISTICS_LIST = 'financial/SORT_PROVIDE_STATISTICS_LIST';
/*permission*/
export const CHANGE_PERMISSION_DATA = 'permission/CHANGE_PERMISSION_DATA';
export const CHANGE_PERMISSION_CLASS_DATA = 'permission/CHANGE_PERMISSION_CLASS_DATA';
/*select*/
export const CHANGE_USER_ID = 'select/CHANGE_USER_ID';
export const CHANGE_SALE_GROUP_ID = 'select/CHANGE_SALE_GROUP_ID';
export const CHANGE_AGENCY_IDS = 'select/CHANGE_AGENCY_IDS';
export const CHANGE_CLIENT_IDS = 'select/CHANGE_CLIENT_IDS';
export const CHANGE_MEDIA_COMPANIES_IDS = 'select/CHANGE_MEDIA_COMPANIES_IDS';
export const CHANGE_MEDIAS_NAMES = 'select/CHANGE_MEDIAS_NAMES';
export const CHANGE_SELECT_PM = 'select/CHANGE_SELECT_PM';


// Mutations
export const MUTATE_LOADING_STATUS = 'MUTATE_LOADING_STATUS';
/*chart*/
export const MUTATE_MONEY_STATUS = 'chart/MUTATE_MONEY_STATUS';
export const MUTATE_MONTH_BALANCE = 'chart/MUTATE_MONTH_BALANCE';
export const MUTATE_CHART_DATA = 'chart/MUTATE_CHART_DATA';
/*dataTable*/
export const MUTATE_TABLE_SELECT = 'chart/MUTATE_TABLE_SELECT';
export const MUTATE_PUSH_TABLE_SELECT = 'chart/MUTATE_PUSH_TABLE_SELECT';
export const MUTATE_SPLICE_TABLE_SELECT = 'chart/MUTATE_SPLICE_TABLE_SELECT';
/*datePick*/
export const MUTATE_DATE = 'datePick/MUTATE_DATE';
/*dateRange*/
export const MUTATE_DATE_RANGE = 'dateRange/MUTATE_DATE_RANGE';
/*exchangeRate*/
export const MUTATE_CHART_EXCHANGE_LINE = 'exchangeRate/MUTATE_CHART_EXCHANGE_LINE';
export const MUTATE_EXCHANGE_RATES_LIST = 'exchangeRate/MUTATE_EXCHANGE_RATES_LIST';
export const MUTATE_CURRENCY = 'exchangeRate/MUTATE_CURRENCY';
/*financial*/
export const MUTATE_PROVIDE_STATISTICS_LIST = 'financial/MUTATE_PROVIDE_STATISTICS_LIST';
export const MUTATE_PROVIDE_TOTAL_MONEY = 'financial/MUTATE_PROVIDE_TOTAL_MONEY';
export const MUTATE_BONUS_TOTAL_MONEY = 'financial/MUTATE_BONUS_TOTAL_MONEY';
export const MUTATE_SALE_GROUP_TOTAL_MONEY = 'financial/MUTATE_SALE_GROUP_TOTAL_MONEY';
export const MUTATE_PROVIDE_BONUS_LIST = 'financial/MUTATE_PROVIDE_BONUS_LIST';
export const MUTATE_PROVIDE_GROUPS_LIST = 'financial/MUTATE_PROVIDE_GROUPS_LIST';
export const MUTATE_PROVIDE_CHAR_BAR_STACK = 'financial/MUTATE_PROVIDE_CHAR_BAR_STACK';
export const MUTATE_SORT_PROVIDE_STATISTICS_LIST = 'financial/MUTATE_SORT_PROVIDE_STATISTICS_LIST';
export const MUTATE_RESET_PROVIDE_CHAR_BAR_STACK = 'financial/MUTATE_RESET_PROVIDE_CHAR_BAR_STACK';
export const MUTATE_STATISTICS = 'financial/MUTATE_STATISTICS';
export const MUTATE_SELECT_DATA = 'financial/MUTATE_SELECT_DATA';
/*permission*/
export const MUTATE_PERMISSION_DATA = 'permission/MUTATE_PERMISSION_DATA';
export const MUTATE_PERMISSION_CLASS_DATA = 'permission/MUTATE_PERMISSION_CLASS_DATA';
/*select*/
export const MUTATE_USER_ID = 'select/MUTATE_USER_ID';
export const MUTATE_SALE_GROUP_ID = 'select/MUTATE_SALE_GROUP_ID';
export const MUTATE_AGENCY_IDS = 'select/MUTATE_AGENCY_IDS';
export const MUTATE_CLIENT_IDS = 'select/MUTATE_CLIENT_IDS';
export const MUTATE_MEDIA_COMPANIES_IDS = 'select/MUTATE_MEDIA_COMPANIES_IDS';
export const MUTATE_MEDIAS_NAMES = 'select/MUTATE_MEDIAS_NAMES';
export const MUTATE_SELECT_PM = 'select/MUTATE_SELECT_PM';
